### ISSUE TITLE
Missing graphics/ViewModule.js

### ISSUE THREAD

**Issue by soon** [CodinGame/SpringChallenge2022#2]
UI fails to load ViewModule.js:

```
GET http://localhost:8888/graphics/ViewModule.js net::ERR_ABORTED 404 (Not Found)
```

And then fails with the following error:

```
jquery.min.js:2 Uncaught Error: [$injector:modulerr] Failed to instantiate module player due to:
Error: [$injector:nomod] Module 'player' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

https://errors.angularjs.org/1.7.8/$injector/modulerr?p0=player&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'player'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.7.8%2F%24injector%2Fnomod%3Fp0%3Dplayer%0A%20%20%20%20at%20https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A138%3A12%0A%20%20%20%20at%20https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A2308%3A17%0A%20%20%20%20at%20ensure%20(https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A2229%3A38)%0A%20%20%20%20at%20module%20(https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A2306%3A14)%0A%20%20%20%20at%20https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A5036%3A22%0A%20%20%20%20at%20forEach%20(https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A387%3A20)%0A%20%20%20%20at%20loadModules%20(https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A5020%3A5)%0A%20%20%20%20at%20createInjector%20(https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A4937%3A19)%0A%20%20%20%20at%20doBootstrap%20(https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A1960%3A20)%0A%20%20%20%20at%20bootstrap%20(https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.7.8%2Fangular.js%3A1981%3A12)
    at angular.js:138:12
    at angular.js:5060:15
    at forEach (angular.js:387:20)
    at loadModules (angular.js:5020:5)
    at createInjector (angular.js:4937:19)
    at doBootstrap (angular.js:1960:20)
    at bootstrap (angular.js:1981:12)
    at angularInit (angular.js:1866:5)
    at HTMLDocument.<anonymous> (angular.js:36430:5)
    at e (jquery.min.js:2:29453)
```

**Comment by CGjupoulton** [comment]
For this repo, ViewModule.js needs to generated from the typescript code; launch `npm ci` and run start` in the `src/main/resources/view/` folder

**Comment by mlomb** [comment]
After generating `ViewModule.js` using `npm ci` and `npm run start` I'm getting the following:

> <Error in module "graphics">
The cacheId "left" does not exist in TextureCache.

I also noticed that some assets are not being loaded:

![image](https://user-images.githubusercontent.com/5845105/164504562-cfdce429-2a93-44b5-9063-804d22664fc4.png)

**Comment by CGjupoulton** [comment]
The request URL should be `http://localhost:8888/assets/beam.png`, `http://localhost:8888/assets/assets/beam.png`. Sounds like a compatibility issue with your environment. Are you on windows?

**Comment by mlomb** [comment]
Yes, I'm on Windows
